/*
 * FrmGeraBoletoBlocoBB.java
 *
 * Created on 12 de Novembro de 2008, 18:37
 */
package org.jboleto.view;

import java.io.File;
import java.io.FileInputStream;
import java.util.ArrayList;
import java.util.Random;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.xml.namespace.QName;
import javax.xml.stream.XMLInputFactory;
import javax.xml.stream.XMLEventReader;
import javax.xml.stream.XMLStreamReader;
import javax.xml.stream.events.StartDocument;
import javax.xml.stream.events.StartElement;
import javax.xml.stream.events.XMLEvent;
import org.jboleto.JBoleto;
import org.jboleto.JBoletoBean;
import org.jboleto.control.Generator;
import org.jboleto.control.PDFGenerator;

/**
 *
 * @author  wanderson
 */
public class BackupBBGeral extends javax.swing.JFrame {

    String data[][] = {{"", "", "", "", "", "", "", "", "", "", "", ""}};
    String col[] = {"Nosso Núm.", "Sacado", "Endereço", "Bairro", "Cidade", "UF", "CEP", "CPF", "Valor", "Convênio", "Carteira", "Vencimento","Mensagem personalizada 1","Mensagem personalizada 2"};
    DefaultTableModel model = new DefaultTableModel(data, col);
    String dataHead[][] = {{"", "", "", "", ""}};
    String colHead[] = {"Agência.", "Conta Corrente", "Dígito verificador", "Data Documento", "Cedente"};
    DefaultTableModel modelHead = new DefaultTableModel(dataHead, colHead);
    JBoletoBean jBoletoBean;

    Generator generator;
    JBoleto jBoleto;
    /** Creates new form FrmGeraBoletoBlocoBB */
    public BackupBBGeral() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jBtnRecuperarXML = new javax.swing.JButton();
        jBtnEscolherArquivo = new javax.swing.JButton();
        jTxtXmlUrl = new javax.swing.JTextField();
        jBtnProcessarBoletos = new javax.swing.JButton();
        jTxtDestinoOutput = new javax.swing.JTextField();
        jBtnLocalOutput = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTblBoletos = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableHead = new javax.swing.JTable();
        jTxtMsg01 = new javax.swing.JTextField();
        jTxtMsg02 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtImagemPropaganda = new javax.swing.JTextField();
        jBtnImagemPropaganda = new javax.swing.JButton();

        setTitle("Geração de Bloquetos de Cobrança em Bloco Bacno do Brasil comvênio de 6 dígitos e tipo de carteira 2");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jBtnRecuperarXML.setLabel("Transferir Dados Para Tabela");
        jBtnRecuperarXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRecuperarXMLActionPerformed(evt);
            }
        });

        jBtnEscolherArquivo.setText("Escolher Arquivo XML");
        jBtnEscolherArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEscolherArquivoActionPerformed(evt);
            }
        });

        jTxtXmlUrl.setEditable(false);

        jBtnProcessarBoletos.setText("Processar Boletos");
        jBtnProcessarBoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProcessarBoletosActionPerformed(evt);
            }
        });

        jBtnLocalOutput.setText("Escolher Destino");
        jBtnLocalOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLocalOutputActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jTblBoletos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblBoletos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane5.setViewportView(jTblBoletos);

        jTableHead.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTableHead);

        jLabel1.setText("Mensagem");

        jLabel2.setText("Mensagem");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtMsg02, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                            .addComponent(jTxtMsg01, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtMsg01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtMsg02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBtnImagemPropaganda.setText("Escolher Imagem");
        jBtnImagemPropaganda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnImagemPropagandaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnEscolherArquivo)
                    .addComponent(jTxtXmlUrl, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addComponent(jBtnRecuperarXML)
                    .addComponent(jBtnProcessarBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTxtImagemPropaganda, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtDestinoOutput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnImagemPropaganda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnLocalOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnEscolherArquivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtXmlUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnRecuperarXML)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtImagemPropaganda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnImagemPropaganda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtDestinoOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnLocalOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnProcessarBoletos)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>
    private void jBtnRecuperarXMLActionPerformed(java.awt.event.ActionEvent evt) {

        final ProgressBar barra = new ProgressBar();
        JFrame frame = new JFrame("Transferindo Dados para a Tabela.... Aguarde....");
        frame.setSize(600, 70);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setContentPane(barra);
        frame.setVisible(true);
        frame.setLocation(400, 300);
        barra.atualizaBarra(1);

        model.setNumRows(0);
        modelHead.setNumRows(0);
        try {
            //-- Necessario para ler o Xml - Stax
            XMLInputFactory fInput = XMLInputFactory.newInstance();
            XMLStreamReader reader = fInput.createXMLStreamReader(new FileInputStream(jTxtXmlUrl.getText()));

            ArrayList listaItens = new ArrayList();
            StringBuilder linhas = new StringBuilder();

            String agencia = null;
            String contaCorrente = null;
            String dvcontacorrente = null;
            String datadocumento = null;
            String cedente = null;

            String msg01 = null;
            String msg02 = null;

            String msg03 = null;
            String msg04 = null;

            String nome = null;
            String endereco = null;
            String bairro = null;
            String cidade = null;
            String uf = null;
            String cep = null;
            String cpf = null;
            String vencimento = null;
            String nossoNumero = null;
            String numConvenio = null;
            String carteira = null;
            String valor = null;

            int i = 1;
            while (reader.hasNext()) {

                final int percent = i;
                barra.atualizaBarra(percent);

                int evento = reader.getEventType();

                if (evento == XMLStreamReader.START_DOCUMENT) {
                    //System.out.println("Iniciou Documento");
                } else if (evento == XMLStreamReader.START_ELEMENT) {
                    //System.out.println("Startou Elemento");
                    String nomeTag = reader.getLocalName();
                    if ("boletos".equals(nomeTag)) {
                        agencia = reader.getAttributeValue(null, "agencia");
                        contaCorrente = reader.getAttributeValue(null, "contacorrente");
                        dvcontacorrente = reader.getAttributeValue(null, "dvcontacorrente");
                        datadocumento = reader.getAttributeValue(null, "datadocumento");
                        cedente = reader.getAttributeValue(null, "cedente");
                        msg01 = reader.getAttributeValue(null, "mensagem01");
                        msg02 = reader.getAttributeValue(null, "mensagem02");
                        System.out.println("Agencia :" + agencia + " - " + "Conta Corrente: " + contaCorrente + "-" + dvcontacorrente + " -" + "Data : " + datadocumento + " - " + cedente);
                    } else if ("NOMSAC".equals(nomeTag)) {
                        nome = reader.getElementText();
                    } else if ("ENDSAC".equals(nomeTag)) {
                        endereco = reader.getElementText();
                    } else if ("BAISAC".equals(nomeTag)) {
                        bairro = reader.getElementText();
                    } else if ("CIDSAC".equals(nomeTag)) {
                        cidade = reader.getElementText();
                    } else if ("UFESAC".equals(nomeTag)) {
                        uf = reader.getElementText();
                    } else if ("CEPSAC".equals(nomeTag)) {
                        cep = reader.getElementText();
                    } else if ("CPFSAC".equals(nomeTag)) {
                        cpf = reader.getElementText();
                    } else if ("VENCIM".equals(nomeTag)) {
                        vencimento = reader.getElementText();
                    } else if ("NOSSON".equals(nomeTag)) {
                        nossoNumero = reader.getElementText();
                    } else if ("NUMCON".equals(nomeTag)) {
                        numConvenio = reader.getElementText();
                    } else if ("CARTEI".equals(nomeTag)) {
                        carteira = reader.getElementText();
                    } else if ("VALORB".equals(nomeTag)) {
                        valor = reader.getElementText();
                    } else if ("MSG03".equals(nomeTag)) {
                        msg03 = reader.getElementText();
                    } else if ("MSG04".equals(nomeTag)) {
                        msg04 = reader.getElementText();
                    }
                } else if (evento == XMLStreamReader.END_ELEMENT) {
                    String nomeTag = reader.getLocalName();
                    if ("boleto".equals(nomeTag)) {

                        model.insertRow(0, new Object[]{nossoNumero, nome, endereco, bairro, cidade, uf, cep, cpf, valor, numConvenio, carteira, vencimento, msg03, msg04});

                        nome = null;
                        endereco = null;
                        bairro = null;
                        cidade = null;
                        uf = null;
                        cep = null;
                        cpf = null;
                        vencimento = null;
                        nossoNumero = null;
                        numConvenio = null;
                        carteira = null;
                        valor = null;
                        msg03 = null;
                        msg04 = null;
                    }
                }
                evento = reader.next();
                i++;
            }
            frame.setVisible(false);
            modelHead.insertRow(0, new Object[]{agencia, contaCorrente, dvcontacorrente, datadocumento, cedente});
            jTxtMsg01.setText(msg01);
            jTxtMsg02.setText(msg02);
            modelHead.removeRow(jTableHead.getRowCount());
        } catch (Exception exception) {
            exception.getMessage();
        }


    //for (int i = 0; i < 10000; i++) {
    //    model.insertRow(0, new Object[]{"8200000001", "WANDERSON CAMARA DOS SANTOS", "AV. SENADOR SALGADO FILHO", "LAGOA NOVA", "NATAL", "RN", "59000000", "00000000011", "180,98", "123456", "10/02/2009"});
    //}
}

    private void jBtnEscolherArquivoActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Selecione o Arquivo Xml Contendo os Dados Para Impressão dos Boletos");
        int result = fileChooser.showOpenDialog(fileChooser);


        if (result == JFileChooser.OPEN_DIALOG) {
            String file = fileChooser.getSelectedFile().getPath();
            jTxtXmlUrl.setText(file);
        }
}

    private void formWindowActivated(java.awt.event.WindowEvent evt) {
        jTblBoletos.setModel(model);
        jTableHead.setModel(modelHead);
    }

    private void jBtnProcessarBoletosActionPerformed(java.awt.event.ActionEvent evt) {

        try {

            final ProgressBar barra = new ProgressBar();
            JFrame frame = new JFrame("Gerando Boletos.... Aguarde....");
            frame.setSize(400, 70);
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setContentPane(barra);
            frame.setVisible(true);
            frame.setLocation(400, 300);

            barra.atualizaBarra(20);

            jBoletoBean = new JBoletoBean();

            jBoletoBean.setDataDocumento("23/10/2008");
            jBoletoBean.setDataProcessamento("23/10/2008");

            jBoletoBean.setCedente("CEDENTE TESTE");
            jBoletoBean.setCarteira("21");

            jBoletoBean.setNomeSacado("SACADO TESTE");
            jBoletoBean.setEnderecoSacado("Av. Teste");
            jBoletoBean.setBairroSacado("Bairro teste");
            jBoletoBean.setCidadeSacado("Estado teste");
            jBoletoBean.setUfSacado("XX");
            jBoletoBean.setCepSacado("59040-580");
            jBoletoBean.setCpfSacado("0000000000000");

            //jBoletoBean.setLocalPagamento("QUALQUER AGENCIA BANCÁRIA ATÉ O VENCIMENTO");
            //jBoletoBean.setLocalPagamento2("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            Vector descricoes = new Vector();
            jBoletoBean.setDescricoes(descricoes);

            jBoletoBean.setDescricoes(descricoes);
            if((!jTxtImagemPropaganda.getText().isEmpty())){
                jBoletoBean.setImagemMarketing(jTxtImagemPropaganda.getText());
            }

            jBoletoBean.setDataVencimento("23/10/2008");
            jBoletoBean.setInstrucao1("");
            jBoletoBean.setInstrucao2("");
            jBoletoBean.setInstrucao3("");
            jBoletoBean.setInstrucao4("");

            jBoletoBean.setAgencia("0000");
            jBoletoBean.setContaCorrente("00000000"); //completar com zeros quando necessario
            jBoletoBean.setDvContaCorrente("X");

            jBoletoBean.setNumConvenio("000000");
            jBoletoBean.setNossoNumero("0000305307", 17);
            jBoletoBean.setValorBoleto("0.00");


            generator = new PDFGenerator(jBoletoBean, JBoleto.BANCO_DO_BRASIL);
            jBoleto = new JBoleto(generator, jBoletoBean, JBoleto.BANCO_DO_BRASIL);
            int cont = 0;
            int num = 1;
            for (int i = 0; i < jTblBoletos.getRowCount(); i++) {

                final int percent = i;
                barra.atualizaBarra(percent);

                jBoleto.addBoleto();

                //-- "Agência.","Conta Corrente", "Dígito verificador", "Data Documento", "Cedente"
                //-- "Nosso Núm.", "Sacado", "Endereço", "Bairro", "Cidade", "UF", "CEP", "CPF", "Valor", "Convênio", "Carteira", "Vencimento"

                jBoletoBean.setDataDocumento(jTableHead.getValueAt(0, 3).toString());
                jBoletoBean.setDataProcessamento(jTableHead.getValueAt(0, 3).toString());

                jBoletoBean.setCedente(jTableHead.getValueAt(0, 4).toString());
                jBoletoBean.setCarteira(jTblBoletos.getValueAt(i, 10).toString());

                jBoletoBean.setNomeSacado(jTblBoletos.getValueAt(i, 1).toString());
                jBoletoBean.setEnderecoSacado(jTblBoletos.getValueAt(i, 2).toString());
                jBoletoBean.setBairroSacado(jTblBoletos.getValueAt(i, 3).toString());
                jBoletoBean.setCidadeSacado(jTblBoletos.getValueAt(i, 4).toString());
                jBoletoBean.setUfSacado(jTblBoletos.getValueAt(i, 5).toString());
                jBoletoBean.setCepSacado(jTblBoletos.getValueAt(i, 6).toString());
                jBoletoBean.setCpfSacado(jTblBoletos.getValueAt(i, 7).toString());

                jBoletoBean.setLocalPagamento("QUALQUER AGENCIA BANCÁRIA ATÉ O VENCIMENTO");
                //-- jBoletoBean.setLocalPagamento2("APOS O VENCIMENTO, SOMENTE NO BANCO DO BRASIL");

                //jBoletoBean.setDescricoes(descricoes);
                if((!jTxtImagemPropaganda.getText().isEmpty())){
                    jBoletoBean.setImagemMarketing(jTxtImagemPropaganda.getText());
                }

                jBoletoBean.setDataVencimento(jTblBoletos.getValueAt(i, 11).toString());
                jBoletoBean.setInstrucao3(jTxtMsg01.getText());
                jBoletoBean.setInstrucao4(jTxtMsg02.getText());
                jBoletoBean.setInstrucao1(jTblBoletos.getValueAt(i, 12).toString());
                jBoletoBean.setInstrucao2(jTblBoletos.getValueAt(i, 13).toString());

                jBoletoBean.setAgencia(jTableHead.getValueAt(0, 0).toString());
                jBoletoBean.setContaCorrente(jTableHead.getValueAt(0, 1).toString()); //completar com zeros quando necessario
                jBoletoBean.setDvContaCorrente(jTableHead.getValueAt(0, 2).toString());

                jBoletoBean.setNumConvenio(jTblBoletos.getValueAt(i, 9).toString());
                jBoletoBean.setNossoNumero(jTblBoletos.getValueAt(i, 0).toString(), 17);
                jBoletoBean.setValorBoleto(jTblBoletos.getValueAt(i, 8).toString());

                cont++;

                if(cont==1000){
                    jBoleto.closeBoleto(jTxtDestinoOutput.getText() + "/" + "BoletosMinervaJAVA" + num + ".pdf");
                    cont = 0;
                    num++;
                    System.gc();
                }
            }
            num++;
            jBoleto.addBoleto();
            jBoleto.closeBoleto(jTxtDestinoOutput.getText() + "/" + "BoletosMinervaJAVA"+ num + ".pdf");
            frame.setVisible(false);
            JOptionPane.showMessageDialog(null, "Arquivo com Boleto Gerado com Sucesso!");
        } catch (Exception exception) {

        }

    }

    private void jBtnLocalOutputActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setDialogTitle("Selecione o diretório de destino do arquivo PDF contendo os Boletos");
        int result = fileChooser.showOpenDialog(fileChooser);

        if (result == JFileChooser.OPEN_DIALOG) {
            File file = fileChooser.getSelectedFile();
            jTxtDestinoOutput.setText(file.getPath());
        }
    }

    private void jBtnImagemPropagandaActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Selecione o Arquivo de Imagem contendo o Marketing a ser Impresso no(s) Boleto(s)");
        int result = fileChooser.showOpenDialog(fileChooser);


        if (result == JFileChooser.OPEN_DIALOG) {
            String file = fileChooser.getSelectedFile().getPath();
            jTxtImagemPropaganda.setText(file);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmGeraBoletoBlocoBB().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton jBtnEscolherArquivo;
    private javax.swing.JButton jBtnImagemPropaganda;
    private javax.swing.JButton jBtnLocalOutput;
    private javax.swing.JButton jBtnProcessarBoletos;
    private javax.swing.JButton jBtnRecuperarXML;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTableHead;
    private javax.swing.JTable jTblBoletos;
    private javax.swing.JTextField jTxtDestinoOutput;
    private javax.swing.JTextField jTxtImagemPropaganda;
    private javax.swing.JTextField jTxtMsg01;
    private javax.swing.JTextField jTxtMsg02;
    private javax.swing.JTextField jTxtXmlUrl;
    // End of variables declaration
}
